sqlite3: &sqlite3
  adapter: sqlite3
  database: db/pagy_test.sqlite3
  pool: 5
  timeout: 5000

postgresql: &postgresql
  adapter: postgresql
  host: localhost
  username: postgres
  password:
  database: pagy_test

mysql: &mysql
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: pagy_test

test:
  <<: *<%= ENV['DB'] %>
